/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtDots: typeof import('./components/Art/ArtDots.vue')['default']
    ArtPlum: typeof import('./components/Art/ArtPlum.vue')['default']
    DarkMode: typeof import('./components/DarkMode.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Logo: typeof import('./components/logo.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PostsList: typeof import('./components/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WrapperPost: typeof import('./components/WrapperPost.vue')['default']
  }
}
