/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/navigator': RouteRecordInfo<'/navigator', '/navigator', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/browser-cache': RouteRecordInfo<'/posts/browser-cache', '/posts/browser-cache', Record<never, never>, Record<never, never>>,
    '/posts/call-apply-bind': RouteRecordInfo<'/posts/call-apply-bind', '/posts/call-apply-bind', Record<never, never>, Record<never, never>>,
    '/posts/debounce-throttle': RouteRecordInfo<'/posts/debounce-throttle', '/posts/debounce-throttle', Record<never, never>, Record<never, never>>,
    '/posts/git-commands': RouteRecordInfo<'/posts/git-commands', '/posts/git-commands', Record<never, never>, Record<never, never>>,
    '/posts/new-create-instanceof': RouteRecordInfo<'/posts/new-create-instanceof', '/posts/new-create-instanceof', Record<never, never>, Record<never, never>>,
    '/posts/prototype-extends': RouteRecordInfo<'/posts/prototype-extends', '/posts/prototype-extends', Record<never, never>, Record<never, never>>,
    '/posts/set-map': RouteRecordInfo<'/posts/set-map', '/posts/set-map', Record<never, never>, Record<never, never>>,
    '/posts/vue-react-perf': RouteRecordInfo<'/posts/vue-react-perf', '/posts/vue-react-perf', Record<never, never>, Record<never, never>>,
    '/posts/web-storage': RouteRecordInfo<'/posts/web-storage', '/posts/web-storage', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
  }
}
